### ISSUE TITLE
several insta

### ISSUE THREAD

**Issue by alex-ash** [Horhik/Instagram2Fedi#5]
Hello!
Is there any way to crosspost from several insta accounts to one pixelfed?

**Comment by Horhik** [comment]
Who prevents you from launching several corsposters at one time? :)
I think you can modify docker-compose file this way:
``` YAML
version: '3'
services:
  bot-1: # FIRST BOT
    build:
      context: .
    image: "horhik/instagram2fedi:latest"
    environment:
      - YOUR_CONTAINER_NAME=<whatever>
      - I2M_INSTAGRAM_USER=<instagram username> # FIRST INSTAGRAM ACCOUNT
      - I2M_INSTANCE=<mastodon or pixelfed instance>
      - I2M_TOKEN=<token> # SAME TOKEN
     # other variables ....

  bot-2: # SECOND BOT
    build:
      context: .
    image: "horhik/instagram2fedi:latest"
    environment:
      - YOUR_CONTAINER_NAME=<whatever>
      - I2M_INSTAGRAM_USER=<instagram username> # SECOND INSTAGRAM ACCOUNT
      - I2M_INSTANCE=<mastodon or pixelfed instance>
      - I2M_TOKEN=<token> # SAME TOKEN
     # other variables ....
```
